### ISSUE TITLE
Fn.bind error

### ISSUE THREAD

**Issue by iAuvic** [Jisagi/Discord-guild-copy#11]
Successfully logged in as botxd#1746. Starting script.
TypeError: fn.bind is not a function
    at Map.find (C:\Users\Defalt\Desktop\Discord-guild-copy-master\Discord-guild
-copy-master\node_modules\discord.js\src\util\Collection.js:171:49)
    at Function.validateSettings (C:\Users\Defalt\Desktop\Discord-guild-copy-mas
ter\Discord-guild-copy-master\objects\validator.js:27:48)
    at Client.client.on (C:\Users\Defalt\Desktop\Discord-guild-copy-master\Disco
rd-guild-copy-master\copy.js:24:47)
    at Client.emit (events.js:187:15)
    at WebSocketConnection.triggerReady (C:\Users\Defalt\Desktop\Discord-guild-c
opy-master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocke
t\WebSocketConnection.js:114:17)
    at WebSocketConnection.checkIfReady (C:\Users\Defalt\Desktop\Discord-guild-c
opy-master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocke
t\WebSocketConnection.js:130:61)
    at GuildCreateHandler.handle (C:\Users\Defalt\Desktop\Discord-guild-copy-mas
ter\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\packe
ts\handlers\GuildCreate.js:14:31)
    at WebSocketPacketManager.handle (C:\Users\Defalt\Desktop\Discord-guild-copy
-master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\p
ackets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Defalt\Desktop\Discord-guild-copy-
master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\We
bSocketConnection.js:316:35)
    at WebSocketConnection.onMessage (C:\Users\Defalt\Desktop\Discord-guild-copy
-master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\W
ebSocketConnection.js:279:10)

Note: I already tried reinstall NodeJS

**Comment by Jisagi** [comment]
1. Delete `node_modules` and rerun `npm install` and then try `node copy.js <command>` and see if it works
2. What version of node.js do you have?

**Comment by iAuvic** [comment]
1. Same error
2. 8.11.2

**Comment by iAuvic** [comment]
Same error with the three options.

**Comment by Jisagi** [comment]
Could you upload the two log files inside the `logs/` folder` on somthing like pastebin? Maybe that'll help find the issue.

**Comment by iAuvic** [comment]
Yesterday, but i'll try again.

Error's: https://pastebin.com/yGqJYd90
Log's: https://pastebin.com/nKVNYMka

**Comment by iAuvic** [comment]
Now i received this error:

Successfully logged in as botxd#1746. Starting script.
Error: Original guild to copy does not exist. Please check if the id in the sett
ings is correct and if the bot is also member of this guild.
    at Client.client.on (C:\Users\Defalt\Desktop\Discord-guild-copy-master\copy.
js:46:23)
    at emitNone (events.js:111:20)
    at Client.emit (events.js:208:7)
    at WebSocketConnection.triggerReady (C:\Users\Defalt\Desktop\Discord-guild-c
opy-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:1
14:17)
    at WebSocketConnection.checkIfReady (C:\Users\Defalt\Desktop\Discord-guild-c
opy-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:1
30:61)
    at GuildCreateHandler.handle (C:\Users\Defalt\Desktop\Discord-guild-copy-mas
ter\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js
:14:31)
    at WebSocketPacketManager.handle (C:\Users\Defalt\Desktop\Discord-guild-copy
-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketMana
ger.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Defalt\Desktop\Discord-guild-copy-
master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:316:3
5)
    at WebSocketConnection.onMessage (C:\Users\Defalt\Desktop\Discord-guild-copy
-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:279:
10)
    at WebSocket.onMessage (C:\Users\Defalt\Desktop\Discord-guild-copy-master\no
de_modules\ws\lib\event-target.js:120:16)


I keep the "originalguild" blank for just clone the guildData

**Comment by Jisagi** [comment]
If you already have the guildData.json file then use `node copy.js restore`. If you don't have it use `node copy.js clone` to create the file and restore the guild.

**Comment by iAuvic** [comment]
Thank you for this awesome script. ^-
