### ISSUE TITLE
Lots of Errors

### ISSUE THREAD

**Issue by ipwnosx** [Jisagi/Discord-guild-copy#110]
[Pterodactyl Daemon]: Finished pulling Docker container image
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
container@pterodactyl~ Server marked as running...
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for discord.js@13.0.0-dev: wanted: {"node":">=14.6.0","npm":">=7.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: discord.js@13.0.0-dev
npm WARN notsup Unsupported engine for @sapphire/async-queue@1.1.4: wanted: {"node":">=14","npm":">=6"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: @sapphire/async-queue@1.1.4
npm WARN notsup Unsupported engine for @discordjs/collection@0.2.1: wanted: {"node":">=14.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: @discordjs/collection@0.2.1
npm WARN notsup Unsupported engine for @discordjs/builders@0.3.0: wanted: {"node":">=14.0.0","npm":">=7.0.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: @discordjs/builders@0.3.0
npm WARN guildcopy@1.5.8 No repository field.

/home/container/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/container/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
/start.sh: line 2: copy.js: command not found
/start.sh: line 3: copy.js: command not found
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from devil38/fork-rewrite 
Digest: sha256:2f7b7ed38069e931e73ac041bfc590714943561a73bdc83f6a9ab65296be62eb 
Status: Image is up to date for registry.gitlab.com/devil38/fork-rewrite:nodejs12 
[Pterodactyl Daemon]: Finished pulling Docker container image
npm WARN guildcopy@1.5.8 No repository field.
container@pterodactyl~ Server marked as running...

/home/container/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/container/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
/start.sh: line 2: copy.js: command not found
/start.sh: line 3: copy.js: command not found
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

*node 12/Ubuntu 20.04*

**Comment by Jisagi** [comment]
Update to nodsjs >=14.0.0 as the read me says and it will work

**Comment by Jisagi** [comment]
lmk if it still doesn't work after the update
