### ISSUE TITLE
awrev

### ISSUE THREAD

**Issue by hecker12423** [Jisagi/Discord-guild-copy#117]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:**

- Node.js version:nodejs: v16.13.0
- Operating system:windows 10
- nodejs: v16.13.0
C:\Users\golah\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128
    const invalidToken = new Error(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\golah\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:26)
    at Client.login (C:\Users\golah\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\node_modules\discord.js\src\client\Client.js:245:21)
    at main (C:\Users\golah\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\copy.js:149:12)
    at Object.<anonymous> (C:\Users\golah\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\copy.js:152:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'

**Comment by Jisagi** [comment]
Either the token you used is actually invalid (try copying it again), or you tried to use a user token, which will not work.

**Comment by Jisagi** [comment]
I will close this issue now. If you still encounter the problem, feel free to reopen it or create a new one.
