### ISSUE TITLE
Error [AuthenticationFailed]:

### ISSUE THREAD

**Issue by xfreezy22** [Jisagi/Discord-guild-copy#133]
**Please describe the problem you are having in detail:**

const invalidToken = new Error(GatewayCloseCodes[GatewayCloseCodes.AuthenticationFailed]);
                         ^

Error [AuthenticationFailed]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\Administrator\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\Administrator\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\client\Client.js:232:21)
    at main (C:\Users\Administrator\Desktop\Discord-guild-copy-master\copy.js:131:12)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Discord-guild-copy-master\copy.js:134:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'AuthenticationFailed'

**Additional information:**

token is valid, tested multiple acc, always getting this error

**Comment by Jisagi** [comment]
You either provided an invalidated/old token or you did you use a user token. Only bot tokens will work with this script
