### ISSUE TITLE
Error running copy.js

### ISSUE THREAD

**Issue by SuperSaiyanBlue** [Jisagi/Discord-guild-copy#17]
I assumed my previous issue was legitimate because of the following error running copy.js:

Script:
C:\Users\myusername\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\copy.js
Line: 1
Char: 1
Error: Syntax error
Code: 800A03EA
Source: Microsoft JScript compilation error

Additionally, when I run node copy.js, I get:
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object. (C:\Users\Downloads\Discord-guild-copy-master\Discord-guild-copy-master\copy.js:3:17)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

May I ask how I resolve these issues? I'm not sure what I did wrong; nodejs is installed. Do I specifically need the 64bit version, as I only have a 32bit PC?

**Comment by SuperSaiyanBlue** [comment]
I've tried the following:
Delete the node_modules folder and re-run npm install
Redownload & reextract the ZIP into a new location and follow setup instructions again
Reinstalling node.js

Nothing seems to be working, and I'm not sure what the problem is.

**Comment by SuperSaiyanBlue** [comment]
Closing this issue as I am stupid. I needed to rune node copy.js [argument] from commandline. I apologize for wasting your time, however I do have one last issue.
