### ISSUE TITLE
newGuild.channels.deleteAll is not a function

### ISSUE THREAD

**Issue by SuperSaiyanBlue** [Jisagi/Discord-guild-copy#18]
When I run the script, either in copy or clone mode, everything works fine until it gets to step 10:

9. Serialization finished and data saved
10. Deleting channels
TypeError: newGuild.channels.deleteAll is not a function
    at Promise (C:\Users\MYNAME\Desktop\Discord-guild-copy-master\Discord-guild-copy-master\objects\cleaner.js:24:53)
    at new Promise (<anonymous>)
    at Function.cleanNewGuild (C:\Users\MYNAME\Desktop\Discord-guild-copy-master\Discord-guild-copy-master\objects\cleaner.js:18:16)
    at Client.client.on (C:\Users\MYNAME\Desktop\Discord-guild-copy-master\Discord-guild-copy-master\copy.js:79:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Is this another EEBKAC error, and I'm just doing something wrong?

**Comment by Jisagi** [comment]
No, that is indeed a bug. It should be fixed with the latest commit i made. You need to redownload the repository now and it should work just fine.

**Comment by SuperSaiyanBlue** [comment]
Thank you, Jisagi! Everything is working fine now, and I apologize for bothering you.
