### ISSUE TITLE
Async problem

### ISSUE THREAD

**Issue by AnonymoCraft** [Jisagi/Discord-guild-copy#22]
I have an error : 
client.on('ready', async () => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by Jisagi** [comment]
Sounds like an old version of node.js. Check with `node -v`. Anything >= 8.0.0 should be fine.

**Comment by AnonymoCraft** [comment]
Thanks, i had node 6
