### ISSUE TITLE
Unexpected token : 

### ISSUE THREAD

**Issue by AnonymoCraft** [Jisagi/Discord-guild-copy#23]
Sorry to ask you another time but i have an problem : (function (exports, require, module, __filename, __dirname) { {"step":9,"general":{"name":"Discordia","region":"eu-west","icon":"https://cdn.discordapp.com/icons/432961277912940545/e57d98d76b1d1eb2eadc1dd71129a67b.png?size=2048","verificationLevel":0,"afkTimeout":300,"explicitContentFilter":0},"roles":[{"idOld":"483925346551463936","name":"f","hexColor":"#000000","hoist":false,"mentionable":false,"position":19,"rawPosition":19,"defaultRole":false,"permBitfield":8},{"idOld":"467725119251546112","name":"BAR","hexColor":"#000000","hoist":false,"mentionable":false,"position":18,"rawPosition":18,"defaultRole":false,"permBitfield":262216},{"idOld":"473987750123798538","name":"Util-dev","hexColor":"#000000","hoist":false,"mentionable":false,"position":17,"rawPosition":17,"defaultRole":false,"permBitfield":262216},{"idOld":"483720663933386753","name":"Commandant","hexColor":"#f1c40f","hoist":true,"mentionable":true,"position":16,"rawPosition":16,"defaultRole"

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Client.client.on (/storage/emulated/0/d/copy.js:60:25)

The file content :
{"step":9,"general":{"name":"Discordia","region":"eu-west","icon":"https://cdn.discordapp.com/icons/432961277912940545/e57d98d76b1d1eb2eadc1dd71129a67b.png?size=2048","verificationLevel":0,"afkTimeout":300,"explicitContentFilter":0},"roles":[{"idOld":"483925346551463936","name":"f","hexColor":"#000000","hoist":false,"mentionable":false,"position":19,"rawPosition":19,"defaultRole":false,"permBitfield":8},{"idOld":"467725119251546112","name":"BAR","hexColor":"#000000","hoist":false,"mentionable":false,"position":18,"rawPosition":18,"defaultRole":false,"permBitfield":262216},{"idOld":"473987750123798538","name":"Util-dev","hexColor":"#000000","hoist":false,"mentionable":false,"position":17,"rawPosition":17,"defaultRole":false,"permBitfield":262216},{"idOld":"483720663933386753","name":"Commandant","hexColor":"#f1c40f","hoist":true,"mentionable":true,"position":16,"rawPosition":16,"defaultRole":false,"permBitfield":104324169},{"idOld":"483720664608407583","name":"Staff","hexColor":"#000000","hoist":false,"mentionable":false,"position":15,"rawPosition":15,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720665019449356","name":"Caporal","hexColor":"#2ecc71","hoist":false,"mentionable":false,"position":14,"rawPosition":14,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720665976012820","name":"Douanier","hexColor":"#e74c3c","hoist":false,"mentionable":false,"position":13,"rawPosition":13,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720666374340646","name":"Bot","hexColor":"#000000","hoist":false,"mentionable":false,"position":12,"rawPosition":12,"defaultRole":false,"permBitfield":104324169},{"idOld":"483720667183972362","name":"Android","hexColor":"#2ecc71","hoist":false,"mentionable":false,"position":11,"rawPosition":11,"defaultRole":false,"permBitfield":104324169},{"idOld":"483720667481505793","name":"Koya","hexColor":"#000000","hoist":false,"mentionable":false,"position":10,"rawPosition":10,"defaultRole":false,"permBitfield":2146958463},{"idOld":"483720668354183188","name":"A vérifier","hexColor":"#95a5a6","hoist":false,"mentionable":false,"position":9,"rawPosition":9,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720669071409172","name":"Soldat","hexColor":"#e91e63","hoist":false,"mentionable":false,"position":8,"rawPosition":8,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720669436051469","name":"Muted","hexColor":"#818386","hoist":false,"mentionable":false,"position":7,"rawPosition":7,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720670044356609","name":"Général","hexColor":"#3498db","hoist":false,"mentionable":false,"position":6,"rawPosition":6,"defaultRole":false,"permBitfield":104324161},{"idOld":"483720670480564236","name":"ThomasDC","hexColor":"#000000","hoist":false,"mentionable":false,"position":5,"rawPosition":5,"defaultRole":false,"permBitfield":104324169},{"idOld":"483720671449317376","name":"Lieutenant","hexColor":"#d7342a","hoist":false,"mentionable":false,"position":4,"rawPosition":4,"defaultRole":false,"permBitfield":262208},{"idOld":"483720672162349076","name":"ToPPazZe","hexColor":"#000000","hoist":false,"mentionable":false,"position":3,"rawPosition":3,"defaultRole":false,"permBitfield":262216},{"idOld":"483720672812597263","name":"BAR","hexColor":"#000000","hoist":false,"mentionable":false,"position":2,"rawPosition":2,"defaultRole":false,"permBitfield":262216},{"idOld":"484833977882902530","name":"guildcopy","hexColor":"#000000","hoist":false,"mentionable":false,"position":1,"rawPosition":1,"defaultRole":false,"permBitfield":8},{"idOld":"432961277912940545","name":"@everyone","hexColor":"#000000","hoist":false,"mentionable":false,"position":0,"rawPosition":0,"defaultRole":true,"permBitfield":8}],"categories":[{"idOld":"483720672686899206","name":"Informations","position":0,"rawPosition":1,"permOverwrites":[]},{"idOld":"483720676495196180","name":"Douane","position":1,"rawPosition":3,"permOverwrites":[]},{"idOld":"483720677812207616","name":"Haut gradés","position":2,"rawPosition":6,"permOverwrites":[]},{"idOld":"483720685299171368","name":"BAR","position":3,"rawPosition":8,"permOverwrites":[]},{"idOld":"483720688453156891","name":"infiltration","position":4,"rawPosition":10,"permOverwrites":[]},{"idOld":"483720691523256335","name":"Données","position":5,"rawPosition":12,"permOverwrites":[]},{"idOld":"483720664054890508","name":"Stage BAR","position":6,"rawPosition":14,"permOverwrites":[]},{"idOld":"483720699530182661","name":"Commandement","position":7,"rawPosition":15,"permOverwrites":[]},{"idOld":"483720700822159376","name":"informations BAR","position":8,"rawPosition":17,"permOverwrites":[]},{"idOld":"483720702051221524","name":"informations stagiaire","position":9,"rawPosition":19,"permOverwrites":[]}],"textChannel":[{"id":"483720665179095040","name":"membres-dangereux","topic":null,"nsfw":false,"isSystemChannel":false,"position":0,"rawPosition":4,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720667238367243","name":"discussion-bar","topic":null,"nsfw":false,"isSystemChannel":false,"position":1,"rawPosition":5,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720667989278742","name":"logs","topic":null,"nsfw":false,"isSystemChannel":false,"position":2,"rawPosition":7,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720669335388174","name":"cancer","topic":null,"nsfw":false,"isSystemChannel":false,"position":3,"rawPosition":9,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720669960601603","name":"blacklist","topic":null,"nsfw":false,"isSystemChannel":false,"position":4,"rawPosition":11,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720671478808596","name":"missions-disponibles","topic":null,"nsfw":false,"isSystemChannel":false,"position":5,"rawPosition":13,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720672124600341","name":"missions-disponibles","topic":null,"nsfw":false,"isSystemChannel":false,"position":6,"rawPosition":16,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720674066694144","name":"secte-d’allthefoxes","topic":null,"nsfw":false,"isSystemChannel":false,"position":7,"rawPosition":18,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720674813149224","name":"legend-ki","topic":null,"nsfw":false,"isSystemChannel":false,"position":8,"rawPosition":20,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720675060875274","name":"fulldeath","topic":null,"nsfw":false,"isSystemChannel":false,"position":9,"rawPosition":21,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720675953999922","name":"questions","topic":null,"nsfw":false,"isSystemChannel":false,"position":10,"rawPosition":22,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720677069946881","name":"serveurs-de-raid-invitation-invalide","topic":null,"nsfw":false,"isSystemChannel":false,"position":11,"rawPosition":23,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720678525370369","name":"kumet","topic":null,"nsfw":false,"isSystemChannel":false,"position":12,"rawPosition":24,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720679091601408","name":"cyberfucker","topic":null,"nsfw":false,"isSystemChannel":false,"position":13,"rawPosition":25,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720679615758366","name":"darksquad","topic":null,"nsfw":false,"isSystemChannel":false,"position":14,"rawPosition":26,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720680529985573","name":"affaire-kanna","topic":null,"nsfw":false,"isSystemChannel":false,"position":15,"rawPosition":27,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720681205268500","name":"serveurs-de-raid","topic":null,"nsfw":false,"isSystemChannel":false,"position":16,"rawPosition":28,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720681616441345","name":"réponsed","topic":null,"nsfw":false,"isSystemChannel":false,"position":17,"rawPosition":29,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720682295787521","name":"screens-secrets","topic":null,"nsfw":false,"isSystemChannel":false,"position":18,"rawPosition":30,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720683126390799","name":"absences","topic":null,"nsfw":false,"isSystemChannel":false,"position":19,"rawPosition":31,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720683487232022","name":"grades","topic":null,"nsfw":false,"isSystemChannel":false,"position":20,"rawPosition":32,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720684611174400","name":"règlement-blacklist","topic":null,"nsfw":false,"isSystemChannel":false,"position":21,"rawPosition":33,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720685852557312","name":"commandes","topic":null,"nsfw":false,"isSystemChannel":false,"position":22,"rawPosition":34,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720686729297920","name":"informations","topic":null,"nsfw":false,"isSystemChannel":false,"position":23,"rawPosition":35,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720687379546112","name":"discussion-stagiaire","topic":null,"nsfw":false,"isSystemChannel":false,"position":24,"rawPosition":36,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720687857434625","name":"urgence-report","topic":null,"nsfw":false,"isSystemChannel":false,"position":25,"rawPosition":37,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720688847290380","name":"as-plateform","topic":null,"nsfw":false,"isSystemChannel":false,"position":26,"rawPosition":38,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720689963237407","name":"shoah-gang","topic":null,"nsfw":false,"isSystemChannel":false,"position":27,"rawPosition":39,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720690390794251","name":"code","topic":null,"nsfw":false,"isSystemChannel":false,"position":28,"rawPosition":40,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720690894241833","name":"magic-hitler-bot","topic":null,"nsfw":false,"isSystemChannel":false,"position":29,"rawPosition":41,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720692295139339","name":"logs-bar","topic":null,"nsfw":false,"isSystemChannel":false,"position":30,"rawPosition":42,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720693318680598","name":"tchernobyl","topic":null,"nsfw":false,"isSystemChannel":false,"position":31,"rawPosition":43,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720693968797712","name":"brigade-d3tr","topic":null,"nsfw":false,"isSystemChannel":false,"position":32,"rawPosition":44,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720694614458388","name":"vcs-bar","topic":null,"nsfw":false,"isSystemChannel":false,"position":33,"rawPosition":45,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720695298129921","name":"surveillance","topic":null,"nsfw":false,"isSystemChannel":false,"position":34,"rawPosition":46,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720696183259136","name":"bots-destructeurs","topic":null,"nsfw":false,"isSystemChannel":false,"position":35,"rawPosition":47,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720696799952896","name":"info-privée","topic":null,"nsfw":false,"isSystemChannel":false,"position":36,"rawPosition":48,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720697584287754","name":"le-royaume","topic":null,"nsfw":false,"isSystemChannel":false,"position":37,"rawPosition":49,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720698229948416","name":"général","topic":null,"nsfw":false,"isSystemChannel":false,"position":38,"rawPosition":50,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720698838253568","name":"frontiere","topic":null,"nsfw":false,"isSystemChannel":false,"position":39,"rawPosition":51,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720699987623947","name":"humour-noir","topic":null,"nsfw":false,"isSystemChannel":false,"position":40,"rawPosition":52,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720701086269466","name":"selfbots","topic":null,"nsfw":false,"isSystemChannel":false,"position":41,"rawPosition":53,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720703158255616","name":"tokens-kanna","topic":null,"nsfw":false,"isSystemChannel":false,"position":42,"rawPosition":54,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720703808372743","name":"règlement-stagiaire","topic":null,"nsfw":false,"isSystemChannel":false,"position":43,"rawPosition":55,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720704328466443","name":"fc-hagra","topic":null,"nsfw":false,"isSystemChannel":false,"position":44,"rawPosition":56,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720705880621057","name":"commandes-bar","topic":null,"nsfw":false,"isSystemChannel":false,"position":45,"rawPosition":57,"parentCat":null,"permLocked":false,"permOverwrites":[]},{"id":"483720706475950082","name":"general","topic":null,"nsfw":false,"isSystemChannel":false,"position":46,"rawPosition":58,"parentCat":null,"permLocked":false,"permOverwrites":[]}],"voiceChannel":[],"emojis":[],"bans":[{"userId":"374997960557199370","reason":"Blacklist bot BAR. motif :  spam "},{"userId":"452895809441103872","reason":"Blacklist bot BAR. motif :  test "}]}

**Comment by AnonymoCraft** [comment]
Very sorry, i solve it. I juste add .json at the end of the file name.
