### ISSUE TITLE
Not work  error in translation.js line 31

### ISSUE THREAD

**Issue by Bartixxx32** [Jisagi/Discord-guild-copy#24]
root@barrax:~/clone2/Discord-guild-copy# node copy.js  clone
/root/clone2/Discord-guild-copy/objects/translator.js:31
    } catch {
            ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)

**Comment by Jisagi** [comment]
Yeah, my bad. I pushed [a commit](https://github.com/Jisagi/Discord-guild-copy/commit/49c80c3da2cd93746dbc6d82c5eda5049615a7ef) with a fix. REdownload the repository and try again
