### ISSUE TITLE
Error when trying to clone

### ISSUE THREAD

**Issue by cristisilaghi** [Jisagi/Discord-guild-copy#29]
For some reason I get this in the console:

> C:\Discord-guild-copy-master>node copy.js clone
> Language English selected. Translated by Jisagi
> Successfully logged in as 1111#1693. Starting script
> Latest script version installed
> Error: New guild admin role id doesn't exist
>     at Function.validateSettings (C:\Discord-guild-copy-master\objects\validator.js:35:39)
>     at Client.client.on (C:\Discord-guild-copy-master\copy.js:59:41)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by cristisilaghi** [comment]
What should I do in this case?!

**Comment by cristisilaghi** [comment]
Oh, I forgot to create the role "guildcopy" or to put newGuildAdminRoleId.
Error message should include more info.
