### ISSUE TITLE
TypeError: NewguildAdminRole.permissions.has is not a function

### ISSUE THREAD

**Issue by J-JSH** [Jisagi/Discord-guild-copy#4]
Keep getting this error TypeError: NewguildAdminRole.permissions.has is not a function

`[28.02.2018 17:20:12] TypeError: newGuildAdminRole.permissions.has is not a function
    at Function.validateSettings (C:\Users\Jake\Desktop\Discord-guild-copy-master\objects\validator.js:35:44)
    at Client.client.on (C:\Users\Jake\Desktop\Discord-guild-copy-master\copy.js.js:24:47)
    at emitNone (events.js:111:20)
    at Client.emit (events.js:208:7)
    at WebSocketConnection.triggerReady (C:\Users\Jake\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:123:17)
    at WebSocketConnection.checkIfReady (C:\Users\Jake\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:139:61)
    at GuildCreateHandler.handle (C:\Users\Jake\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (C:\Users\Jake\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Jake\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\Jake\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)`

**Comment by Jisagi** [comment]
1. Check if there is a role called 'guildcopy' (all lower case) on the new guild and does it have the ADMINITRATOR permission. (If you are using the role id in the settings, just leave that blank.)
2. Did you run `npm install` just now or was this perhaps an older installation. If so, please delete the node_modules folder and rerun `npm install`.

Did you try using the 'newGuildAdminRoleId' in the settings or via the 'guildcopy' named role on the new guild, because i can't think of a case where this could happen.

**Comment by J-JSH** [comment]
I had tried both methods. The pre-existing 'guilcopy' administrator role, and  the RoleID method. hadn't had successful results either way, it has risen the same error. I already had npm but had done an update and ran it again several times throughout, trying to sort out the problem.

**Comment by Jisagi** [comment]
Would you mind adding me on discord? That might be a faster way to try out a few things and get it resolved.
Jisagi#0230
