### ISSUE TITLE
Error trying to copy

### ISSUE THREAD

**Issue by CalvinMJB** [Jisagi/Discord-guild-copy#40]
Happens when I run "node copy.js clone" bot doesn't even start.

C:\Users\Calvin\Desktop\Discord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:171
        this.off(ShardEvents.CLOSE, onClose);
             ^

TypeError: this.off is not a function
    at WebSocketShard.onReady (C:\Users\Calvin\Desktop\Discord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:171:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at WebSocketShard.emit (events.js:208:7)
    at WebSocketShard.onPacket (C:\Users\Calvin\Desktop\Discord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:339:14)
    at WebSocketShard.onMessage (C:\Users\Calvin\Desktop\Discord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:264:10)
    at WebSocket.onMessage (C:\Users\Calvin\Desktop\Discord\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (C:\Users\Calvin\Desktop\Discord\node_modules\ws\lib\websocket.js:789:20)

**Additional information:**
I've updated discord.js and tried clean wiping the files but same issues.

- Node.js version: v8.15.0
- Operating system: Windows 10

**Comment by CalvinMJB** [comment]
Fixed it by updating Node JS Version

**Comment by Jisagi** [comment]
They seemed to have changed their [ci tests](https://github.com/discordjs/discord.js/commit/d057a5040cc372946a341c0b211cd93ea1beb299) to node 10 and 11 as well. They still list node v8.0.0 as requirement, but good to know that this might not be the case anymore now.
