### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Dany-LF** [Jisagi/Discord-guild-copy#60]
1. Serializing general data
2. Serializing role data
TypeError: Cannot read property 'id' of undefined
    at roleCol.map.role (/home/root2/Bureau/Discord-guild-copy-master/objects/serializer.js:103:57)

**Comment by Jisagi** [comment]
Please redownload the latest version of the script. In theory it should know you are not using the latest version, because this error was fixed a while ago. I don't encounter the error when I try it.
Just try again with the latest version and report if it still doesn't work.

**Comment by Dany-LF** [comment]
This is the latest version, I downloaded it yesterday..

**Comment by Jisagi** [comment]
:thinking: Ok, then this is indeed strange. Judging from the line and position this error occurs, it can't be anything else than the script not being able to get the id of the @everyone role. This was an error before, so I assumed it has to be the sam here as well. I am not really ure what this could be except an outdated version of either the script or the discord.js library (or both).
For the sake of trying, can you reinstall both? I'm really out of ideas what else it could be without knowing more.

**Comment by Dany-LF** [comment]
But i have nodejs: v10.16.1
And discord.js v12

**Comment by Dany-LF** [comment]
```js
{
                        // Create new role
                        let newRole = {
                            data: {
                                name: role.name,
                                color: role.hexColor,
                                hoist: role.hoist,
                                mentionable: role.mentionable,
                                permissions: role.permBitfield,
                            },
                        };

                        let promise = newGuild.roles.create(newRole).then(createdRole => {
                            if (debug) Logger.logMessage(translator.disp('messageCreatorRoleDataDebug', [guildData.step - 1, counter++, createdRole.name]));
                            roleReferences.set(role.idOld, { new: createdRole, old: role });
                        });
                        promises.push(promise);
                    }```


why i have:

```
15.1 Created role "new role"
15.2 Created role "new role"
15.3 Created role "new role"
15.4 Created role "new role"
15.5 Created role "new role"
15.6 Created role "new role"
15.7 Created role "new role"```


These are not the names indicated in the server or in the guilddata.json

**Comment by Dany-LF** [comment]
I have this issue and 

TypeError: Cannot read property 'id' of undefined
    at category.permOverwrites.map.permOver (/home/root2/Bureau/Discord-guild-copy-master/objects/creator.js:184:80)

```js
let overwrites = category.permOverwrites.map(permOver => {
                        return {
                            id: guildData.references.roles.get(permOver.id).new.id, //This line
                            allow: new Permissions(permOver.allowed),
                            deny: new Permissions(permOver.denied),
                        };
                    });
```

**Comment by Jisagi** [comment]
To be honest, I have no idea why it does not work. As I said before though, please try to reinstall the discord.js library (and the script). It's done it under a minute and the only real indication why it doesn't work, especially because the first issue was indeed a library issue before. How did you install discord.js?

**Comment by Dany-LF** [comment]
With npm i --save discord.js and package.json:

"discord.js": "git://github.com/hydrabolt/discord.js.git#master",

**Comment by Dany-LF** [comment]
And please accept my fr.json translation :/

**Comment by Jisagi** [comment]
Then you didn't read the instructions. It clearly states, that you should only run `npm install` (or npm i). If you manually install d.js, it will NOT work. Additionally you even used `--save` which might have changed the package.json as well. Redownload the script to be sure and only run `npm install`.

**Comment by Dany-LF** [comment]
We agree that this is good?


```json
{
  "name": "guildcopy",
  "version": "1.4.4",
  "description": "A tool to copy a discord guild",
  "main": "copy.js",
  "scripts": {
    "backup": "node copy.js backup",
    "restore": "node copy.js restore",
    "clone": "node copy.js clone"
  },
  "author": "Jisagi",
  "license": "GPL-3.0",
  "dependencies": {
    "@yarnpkg/lockfile": "^1.1.0",
    "discord.js": "git://github.com/hydrabolt/discord.js.git#master",
    "fs": "0.0.1-security",
    "path": "^0.12.7",
    "request": "^2.88.0"
  }
}
```

**Comment by Dany-LF** [comment]
Seriously... I didn't save the translation I don't want to do it all over again...

**Comment by Jisagi** [comment]
That package.json looks modified. Not sure why fs and path are present as dependencies, but as long as discord.js has the correct reference (which it does) it should be fine.

**Comment by Dany-LF** [comment]
However, this is not going well.

**Comment by Jisagi** [comment]
I did add you on Discord. Let's find out directly why it doesn't work. Remote diagnosis won't help us anymore I guess.

**Comment by Dany-LF** [comment]
Okay

**Comment by Jisagi** [comment]
Used a user account ...
