### ISSUE TITLE
CLIENT_MISSING_INTENTS

### ISSUE THREAD

**Issue by base2code** [Jisagi/Discord-guild-copy#99]
**Please describe the problem you are having in detail:**

When I try to run the command it gives me the following error:

```javascript
(base) niklasgrenningloh@MacBook-Pro Discord-guild-copy % node copy.js 
/Users/niklasgrenningloh/Downloads/Discord-guild-copy/node_modules/discord.js/src/client/Client.js:461
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (/Users/niklasgrenningloh/Downloads/Discord-guild-copy/node_modules/discord.js/src/client/Client.js:461:13)
    at new Client (/Users/niklasgrenningloh/Downloads/Discord-guild-copy/node_modules/discord.js/src/client/Client.js:76:10)
    at Object.<anonymous> (/Users/niklasgrenningloh/Downloads/Discord-guild-copy/copy.js:13:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
```

**Additional information:**

I've turned on both intents:
<img width="994" alt="Bildschirmfoto 2021-02-22 um 17 21 53" src="https://user-images.githubusercontent.com/51596575/108737024-7794ff00-7532-11eb-811d-630db9067bfc.png">

- Node.js version: v15.7.0
- Operating system: macOS Big Sur

**Comment by base2code** [comment]
The bot has the Administrator permission on both servers

**Comment by base2code** [comment]
Duplicate of #98

**Comment by Jisagi** [comment]
Just to let you know: I'm working on it, should be done in a few minutes

**Comment by Jisagi** [comment]
Fixed now, please redownload the repository
